<?php
/**
 * Return the default options of the theme
 * 
 * @return  void
 */

function themesflat_customize_default($key) {
	$default = array(
		'social_links'	=> array ("facebook" => '#', "linkedin" => '#', "twitter"  => '#', "instagram" => '#'),
		'show_social_share' => 0,		
		'social_footer' => 0,
		'go_top' => 1,
		'topbar_background_color'	=> '',
		'topbar_label_address'	=> 'Address',
		'topbar_textcolor'	=> '',
		'topbar_link_color' => '',
		'topbar_link_color_hover' => '',
		'topbar_show' => 0 ,
		'social_topbar' => 1,
		'topbar_address_active' => 1,
		'topbar_date_active' => 1,
		'topbar_phone_active' => 1,
		'typography_topbar' => array(
			'family' => 'Inter',
			'style'  => '400',
			'size'   => '14',
			'line_height'=>'1.4285714285714286em',
		),
		'topbar_controls' => array('padding-top' => '','padding-bottom' => ''),
		'logo_controls' => array('padding-top' => '','padding-bottom' => ''),
		'style_header'	=> 'header-default',	
		'style_topbar'	=> 'topbar-default',	
		'header_backgroundcolor'=>'',
		'header_sticky' => 0,
		'header_search_box' => 0,
		'header_absolute'	=> 0,		
		'header_socials' => 0,
		'header_button' => 1,
		'header_user' => 1,
		'header_favorite' => 0,
		'infor_menu_mobile_show' => 1,
		'header_button_text' => '<i class="icon-autodeal-car"></i> Add listing',
		'header_button_url' => '#',
		'information_datetime' => 'Mon - Sat 8.00 - 18.00',
		'information_email' => 'Contact@gmail.com',
		'information_phone' => '(808) 555-0111',
		'information_address' => '2972 Westheimer Rd. Santa Ana, Illinois 85486 ',
		'show_entry_footer_content'	=> 0,
		'logo_width' => 180,
		'menu_location_primary' => 'primary',
		'site_logo'	=> THEMESFLAT_LINK . 'images/logo.png',
		'site_logo_fixed'	=> THEMESFLAT_LINK . 'images/logo.png',
		'site_logo_mobile'	=> THEMESFLAT_LINK . 'images/logo.png',	
		'site_logo_footer'	=> THEMESFLAT_LINK . 'images/logo-white.png',
		'show_bottom' => 1,		
		'header_backgroundcolor_sticky'=>'',		
		'primary_color'=>'#FF7101',
		'typography_body' => array(
			'family' => 'Outfit',
			'style'  => '400',
			'size'   => '14',
			'line_height'=>'1.4285714285714286em',
		),
		'body_text_color'=>'#696665',
		'body_background_color' => '',
		'page_sidebar_layout' => 'fullwidth',
		'content_controls' => array('padding-top' => 60,'padding-bottom' => 60),
		'typography_menu' => array(
			'family' => 'Outfit',
			'style'  => '500',
			'size'   => '16',
			'line_height'=>'98px',
		), 
		'mainnav_color'		=> '',
		'mainnav_hover_color'=>'#FF7101',
		'mainnav_active_color'=>'#FF7101',
		'menu_distance_between' => 20,
		'typography_sub_menu' => array(
			'family' => 'Outfit',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'1.4',
		),
		'sub_nav_color'		=>'',		
		'sub_nav_color_hover'	=>	'',
		'sub_nav_background'=>'#ffffff',
		'sub_nav_background_hover'=>'',
		'sub_nav_border_color' => '#fff',
		'typography_headings'	=> array(
			'family' => 'Outfit',
			'style'  => '500',
			'line_height'=>'1.2',
		),
		'h1_size' => 40,
		'h2_size' => 30,
		'h3_size' => 24,
		'h4_size' => 20,
		'h5_size' => 18,
		'h6_size' => 16,
		'typography_blockquote' => array(
			'family' => 'Outfit',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'1.4',
		),	
		'typography_blog_post_title' => array(
			'family' => 'Outfit',
			'style'  => '500',
			'size'   => '24',
			'line_height'=>'1.26',
		),
		'typography_blog_post_meta' => array(
			'family' => 'Outfit',
			'style'  => '500',
			'size'   => '14',
			'line_height'=>'1.5384615384615385',
		),
		'typography_blog_post_buttons' => array(
			'family' => 'Outfit',
			'style'  => '600',
			'size'   => '14',
			'line_height'=>'1.5714285714285714',
		),
		'typography_blog_single_title' => array(
			'family' => 'Outfit',
			'style'  => '600',
			'size'   => '40',
			'line_height'=>'1.2',
		),
		'typography_blog_single_comment_title' => array(
			'family' => 'Outfit',
			'style'  => '500',
			'size'   => '30',
			'line_height'=>'1.26',
		),
		'typography_sidebar_widget_title' => array(
			'family' => 'Outfit',
			'style'  => '500',
			'size'   => '24',
			'line_height'=>'1.26',
		),	
		'typography_footer_widget_title' => array(
			'family' => 'Outfit',
			'style'  => '500',
			'size'   => '20',
			'line_height'=>'1.5',
		),	
		'typography_page_title'	=> array(
			'family' => 'Outfit',
			'style'  => '600',
			'size'   => '40',
			'line_height'=>'1.2',
		),
		'page_title_background_color' => '#fff',
		'page_title_background_color_opacity' => '100',
		'page_title_text_color' => '#24272C',		
		'page_title_controls' => array('padding-top' => 0, 'padding-bottom' => 0),
		'page_title_background_image' => '',
		'page_title_image_size' => 'cover',
		'page_title_styles' => 'default',
		'page_title_heading_enabled' => 1,
		'typography_breadcrumb'	=> array(
			'family' => 'Inter',
			'style'  => '400',
			'size'   => '12',
			'line_height'=>'1.4000000000000001',
		),
		'bread_crumb_prefix' =>'',
		'breadcrumb_separator' =>  '<i class="icon-autodeal-angle-right"></i>',
		'breadcrumb_color' => '#B6B6B6',
		'typography_buttons' => array(
			'family' => 'Outfit',
			'style'  => '500',
			'size'   => '16',
			'line_height'=>'',
		),
		'typography_pagination'	=> array(
			'family' => 'Outfit',
			'style'  => '500',
			'size'   => '16',
			'line_height'=>'1.5',
		),		
		'typography_bottom_menu' => array(
			'family' => 'Outfit',
			'style'  => '400',
			'size'   => '18',
			'line_height'=>'1.5',
		),
		'breadcrumb_enabled' => 1,
		'show_post_paginator' => 1,
		'blog_grid_columns' => 2,
		'post_content_elements' => 'title,meta,excerpt_content',
		'meta_elements' => 'category,date',
		'blog_archive_exclude' => '',
		'blog_featured_title' => 'Blog Details',
		'sidebar_layout' => 'sidebar-right',
		'blog_archive_layout' => 'blog-list',
		'blog_sidebar_list'		  => 'blog-sidebar',	
		'blog_layout_single'		  => 'sidebar-right',	
		'blog_archive_readmore' => 0,
		'blog_archive_post_excepts_length' => 25,
		'blog_archive_readmore_text' => 'Read More',
		'blog_archive_pagination_style' => 'pager-numeric',
		'blog_posts_per_page'	=> 3,
		'blog_order_by'	=> 'date',
		'blog_order_direction' => 'DESC',
		'page_sidebar_list'	=> 'blog-sidebar',	

		'feature_form_login' => '',
		'feature_form_register' => '',

		'typography_footer' => array(
			'family' => 'Outfit',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'22.4px',
		),
		'show_footer' => 1,
		'footer_background_color'	=> '#24272C',
		'footer_title_widget_color' => '#fff',
		'footer_text_color'			=> 'rgba(255, 255, 255, 0.5)',
		'footer_text_color_hover'   => '',
		'footer_controls' => array('padding-top' => 38, 'padding-bottom' => 39),
		'tab_footer' => 0,
		'footer_widget_areas' => 4,
		'footer1' => 'footer-1',
		'footer2' => 'footer-2',
		'footer3' => 'footer-3',
		'footer4' => 'footer-4',
		'footer_background_image' => '',
		'footer_image_size' => 'cover',
		'typography_bottom_copyright' => array(
			'family' => 'Inter',
			'style'  => '400',
			'size'   => '14',
			'line_height'=>'21px',
		),
		'bottom_background_color'	=> '#24272C',
		'bottom_text_color'			=> '#fff',
		'bottom_link_color'         => '#fff',
		'bottom_text_color_hover'   => '',		
		'social_bottom'   => 0,		
		'layout_version'			=> 'wide',		
		'footer_copyright'			=> '© 2024 Auto Decar. All rights reserved',
		'enable_preload' => 1,
		'page_title_alignment' => 'left',
		'show_icon_information'	=> 0,
		'footer_info_image'   => THEMESFLAT_LINK . 'images/information-box/icon-1.png',		
		'footer_info_text'   => 'Top 1 Americas',		
		'footer_info_description'   => 'Largest Auto portal',		
		'footer_info_image2'   => THEMESFLAT_LINK . 'images/information-box/icon-2.png',		
		'footer_info_text2'   => 'Car Sold',		
		'footer_info_description2'   => 'Every 5 minute',
		'footer_info_image3'   => THEMESFLAT_LINK . 'images/information-box/icon-3.png',		
		'footer_info_text3'   => 'Offers',		
		'footer_info_description3'   => 'Stay updated pay less',
		'footer_info_image4'   => THEMESFLAT_LINK . 'images/information-box/icon-4.png',		
		'footer_info_text4'   => 'Compare',		
		'footer_info_description4'   => 'Decode the right car',	


		//Dashboard
		'site_logo_dashboard'	=> THEMESFLAT_LINK . 'images/logo-white.png',	

	);
	return $default[$key];
}