<?php
return array(
	'title'  => esc_html__( 'Setup Page', 'tf-car-listing' ),
	'id'     => 'setup-page-options',
	'desc'   => '',
	'icon'   => 'el el-link',
	'fields' => array(
		array(
			'id'      => 'add_listing_page',
			'type'    => 'select',
			'title'   => esc_html__( 'Add Listing', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at add listing page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
		array(
			'id'      => 'my_listing_page',
			'type'    => 'select',
			'title'   => esc_html__( 'My Listing', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at my listing page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
		array(
			'id'      => 'my_profile_page',
			'type'    => 'select',
			'title'   => esc_html__( 'My Profile', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at my profile page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
		array(
			'id'      => 'my_favorites_page',
			'type'    => 'select',
			'title'   => esc_html__( 'My Favorites', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at my favorites page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
		array(
			'id'      => 'my_reviews_page',
			'type'    => 'select',
			'title'   => esc_html__( 'My Reviews', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at my reviews page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
		array(
			'id'      => 'advanced_search_page',
			'type'    => 'select',
			'title'   => esc_html__( 'Advanced Search', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at advanced search page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
		array(
			'id'      => 'my_saved_advanced_searches_page',
			'type'    => 'select',
			'title'   => esc_html__( 'My Saved Searches', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at my saved searches page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
		array(
			'id'      => 'login_page',
			'type'    => 'select',
			'title'   => esc_html__( 'Login', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at login page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
		array(
			'id'      => 'register_page',
			'type'    => 'select',
			'title'   => esc_html__( 'Register', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at register page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
		array(
			'id'      => 'compare_page',
			'type'    => 'select',
			'title'   => esc_html__( 'Compare', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at compare page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
		array(
			'id'      => 'dashboard_page',
			'type'    => 'select',
			'title'   => esc_html__( 'Dashboard', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at dashboard page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
		array(
			'id'      => 'listing_page',
			'type'    => 'select',
			'title'   => esc_html__( 'Listing', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at listing page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
		array(
			'id'      => 'payment_term_condition',
			'type'    => 'select',
			'title'   => esc_html__( 'Payment Terms & Conditions', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at payment terms & conditions page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
		array(
			'id'      => 'package_page',
			'type'    => 'select',
			'title'   => esc_html__( 'Package', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at package page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
		array(
			'id'      => 'payment_invoice_page',
			'type'    => 'select',
			'title'   => esc_html__( 'Payment Invoice', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at payment invoice page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
		array(
			'id'      => 'payment_completed_page',
			'type'    => 'select',
			'title'   => esc_html__( 'Payment Completed', 'tf-car-listing' ),
			'desc'    => esc_html__( 'Select page to show at payment completed page', 'tf-car-listing' ),
			'options' => tfcl_get_all_pages(),
		),
	)
);